<?php

	defined('API_SUCCESS_RESPONSE') OR define('API_SUCCESS_RESPONSE', 1);
	defined('API_FAILURE_RESPONSE') OR define('API_FAILURE_RESPONSE', 0);

	defined('ERROR_STATUS_CODE') OR define('ERROR_STATUS_CODE', 401);
	defined('SUCCESS_STATUS_CODE') OR define('SUCCESS_STATUS_CODE', 200);

	defined('SEARCH_RADIUS') OR define('SEARCH_RADIUS', 5);

	defined('FCM_SERVER_KEY') OR define('FCM_SERVER_KEY', 'AAAAUP94d7Q:APA91bGM8VloJhO4IaWCaywyeriYQV64O3NaDCNugxypqAquqKnqTp9bG5tjynR-_uFhlI-Wsp2hzT6SmAePRGZHs6JbhhEnD-Y7ZQyi4_fL05EpBYE68BSSbw4XRfSJE9g73jGYGgJK');

	defined('DEVICE_PLATFORM_IOS') OR define('DEVICE_PLATFORM_IOS', 1);
	defined('DEVICE_PLATFORM_ANDROID') OR define('DEVICE_PLATFORM_ANDROID', 2);

	defined('ORDER_NOTIFICATION_CASE') OR define('ORDER_NOTIFICATION_CASE', 1);

	defined('ORDER_PENDING_STATUS') OR define('ORDER_PENDING_STATUS', 1);
	defined('ORDER_READY_STATUS') OR define('ORDER_READY_STATUS', 2);
	defined('ORDER_COMPLETED_STATUS') OR define('ORDER_COMPLETED_STATUS', 3);
	defined('ORDER_DECLINED_STATUS') OR define('ORDER_DECLINED_STATUS', 4);
	defined('ORDER_ONDELIVERY_STATUS') OR define('ORDER_ONDELIVERY_STATUS', 5);

	defined('MUTE_NOTIFICATION_FALSE') OR define('MUTE_NOTIFICATION_FALSE', 0);
	defined('MUTE_NOTIFICATION_TRUE') OR define('MUTE_NOTIFICATION_TRUE', 1);
?>